##### JoyOS User Makefile ####

# Name of this project (no spaces or extension)
TARGET = test0

# Source files - list all your .c files here (separated by spaces)
SRC = test0.c

# USB-Serial port number for programming the happyboard
PORT = com4

# Top level JoyOS directory
TOPDIR = ../../

# Extra libraries
EXTRALIBS =

# Include support makefile
include ../makedefaults.inc
